language: python

python:
  - "3.6"

install:
  # install latest release version
  - wget -qO- https://api.github.com/repos/gohugoio/hugo/releases/latest | sed -r -n '/browser_download_url/{/Linux-64bit.deb/{s@[^:]*:[[:space:]]*"([^"]*)".*@\1@g;p}}' | xargs wget
  - sudo dpkg -i hugo*.deb
  - pip install Pygments

script:
  - hugo

deploy:
    - provider: script
      script: bash deploy.sh
      skip_cleanup: true
      on:
        branch: master
