baseurl = "https://www.graphql-java-kickstart.com/docs/graphql-java-servlet/"
languageCode = "en-us"
title = "GraphQL Java Servlet"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "GraphQL Java Kickstart"
	description = "Documentation for GraphQL Java Servlet"
	copyright = "Released under the Apache 2.0 license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/graphql-java-kickstart/graphql-java-servlet"

	version = "6.2.0"
	logo = "images/logo-graphql-kickstart-2000px.png"
	favicon = "images/favicon.ico"

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = "stylesheets/androidstudio.css"

	[params.palette]
    	primary = "pink"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "graphql-java-kickstart"
	email   = ""


[[menu.main]]
	name   = "About"
	url    = "about/"
	weight = 1

[[menu.main]]
	name   = "Getting started"
	url    = "getting-started/"
	weight = 10



[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
